Repository hjcdg1/fosslight, pull requests merged in 2023-10, with the labels that each got.

#2 Set FOSSLight Hub Lite project (#1)
  lite/.eslintrc.json
  lite/.gitignore
  lite/.prettierrc
  lite/README.md
  lite/app/favicon.ico
  lite/app/globals.css
  lite/app/layout.tsx
  lite/app/page.tsx
  lite/components/providers.tsx
  lite/next.config.js
  lite/package-lock.json
  lite/package.json
  lite/postcss.config.js
  lite/public/next.svg
  lite/public/vercel.svg
  lite/tailwind.config.ts
  lite/tsconfig.json
Labels: Add

#8 Remove commit message length check (#6)
  .github/workflows/pull-request.yml
Labels: Remove

#10 Add `lite` to paths-ignore in CI trigger (#9)
  .github/workflows/pull-request.yml
Labels: Add

#5 Construct the base of website design (template) (#4)
  lite/app/(auth)/layout.tsx
  lite/app/(auth)/reset-password/page.tsx
  lite/app/(auth)/sign-in/page.tsx
  lite/app/(auth)/sign-up/page.tsx
  lite/app/(main)/database/license/page.tsx
  lite/app/(main)/database/oss/page.tsx
  lite/app/(main)/database/vulnerability/page.tsx
  lite/app/(main)/etc/code/page.tsx
  lite/app/(main)/etc/user/page.tsx
  lite/app/(main)/layout.tsx
  lite/app/(main)/page.tsx
  lite/app/(main)/self-check/project/page.tsx
  lite/app/favicon.ico
  lite/app/globals.css
  lite/app/layout.tsx
  lite/app/page.tsx
  lite/components/full-search-bar.tsx
  lite/components/side-bar.tsx
  lite/lib/fonts.ts
  lite/public/fonts/SourceSansPro-Black.ttf
  lite/public/fonts/SourceSansPro-Bold.ttf
  lite/public/fonts/SourceSansPro-Light.ttf
  lite/public/fonts/SourceSansPro-Regular.ttf
  lite/public/fonts/SourceSansPro-Semibold.ttf
  lite/public/images/logo.png
  lite/public/next.svg
  lite/public/vercel.svg
  lite/tailwind.config.ts
Labels: Add

#15 Construct the template for mobile (#12)
  lite/app/(main)/layout.tsx
  lite/app/(main)/page.tsx
  lite/app/(main)/project/page.tsx
  lite/app/(main)/self-check/project/page.tsx
  lite/app/globals.css
  lite/app/layout.tsx
  lite/components/bottom-bar.tsx
  lite/components/full-search-bar.tsx
  lite/components/side-bar.tsx
  lite/components/top-bar.tsx
  lite/lib/atoms.ts
  lite/lib/literals.ts
  lite/package-lock.json
  lite/package.json
  lite/tailwind.config.ts
Labels: Add

#17 Construct the template for list pages (#16)
  lite/app/(auth)/layout.tsx
  lite/app/(main)/database/oss/page.tsx
  lite/app/(main)/layout.tsx
  lite/components/bottom-bar.tsx
  lite/components/list-filters.tsx
  lite/components/list-table.tsx
  lite/components/side-bar.tsx
  lite/lib/commons.ts
  lite/public/images/excel.png
  lite/tailwind.config.ts
Labels: Add

#22 Implement dynamic features of list pages (#21)
  lite/@types/globals.d.ts
  lite/app/(main)/database/oss/page.tsx
  lite/app/(main)/layout.tsx
  lite/components/bottom-bar.tsx
  lite/components/full-search-bar.tsx
  lite/components/list-filters.tsx
  lite/components/list-table.tsx
  lite/components/loading.tsx
  lite/components/side-bar.tsx
  lite/lib/atoms.ts
  lite/lib/filters.ts
  lite/package-lock.json
  lite/package.json
Labels: Add

#24 Apply common features to list pages (#23)
  lite/@types/globals.d.ts
  lite/app/(main)/database/license/page.tsx
  lite/app/(main)/database/oss/page.tsx
  lite/app/(main)/database/vulnerability/page.tsx
  lite/app/(main)/self-check/page.tsx
  lite/components/list-filters.tsx
  lite/components/list-table.tsx
Labels: Add

#26 Implement the dashboard page - Part 1 (#25)
  lite/app/(main)/page.tsx
  lite/components/bottom-bar.tsx
Labels: Add

#30 Miscellaneous tasks (#29)
  lite/app/(main)/database/vulnerability/page.tsx
  lite/app/(main)/page.tsx
  lite/app/(main)/search/page.tsx
  lite/components/side-bar.tsx
  lite/components/top-bar.tsx
Labels: Add

#33 Define frequently-used CSS as utility classes (#32)
  lite/app/(auth)/reset-password/page.tsx
  lite/app/(auth)/sign-in/page.tsx
  lite/app/(auth)/sign-up/page.tsx
  lite/app/(main)/database/license/page.tsx
  lite/app/(main)/database/oss/page.tsx
  lite/app/(main)/database/vulnerability/page.tsx
  lite/app/(main)/layout.tsx
  lite/app/(main)/page.tsx
  lite/app/(main)/search/page.tsx
  lite/app/(main)/self-check/page.tsx
  lite/app/globals.css
  lite/components/bottom-bar.tsx
  lite/components/full-search-bar.tsx
  lite/components/list-filters.tsx
  lite/components/list-sections.tsx
  lite/components/list-table.tsx
  lite/components/side-bar.tsx
  lite/components/top-bar.tsx
Labels: Improve

#35 Implement core UI of the self-check detail page (#34)
  lite/@types/globals.d.ts
  lite/app/(main)/database/license/page.tsx
  lite/app/(main)/database/oss/page.tsx
  lite/app/(main)/database/vulnerability/page.tsx
  lite/app/(main)/page.tsx
  lite/app/(main)/search/page.tsx
  lite/app/(main)/self-check/[id]/page.tsx
  lite/app/(main)/self-check/page.tsx
  lite/components/full-search-bar.tsx
  lite/components/list-sections.tsx
  lite/components/list-table.tsx
  lite/components/self-check-notice.tsx
  lite/components/self-check-oss.tsx
  lite/components/self-check-package.tsx
  lite/lib/literals.ts
Labels: Add
