Repository hjcdg1/fosslight, pull requests merged in 2023-12, with the labels that each got.

#44 Add listing apis (#14)
  lite/app/(main)/database/license/page.tsx
  lite/app/(main)/database/oss/page.tsx
  lite/app/(main)/database/vulnerability/page.tsx
  lite/package-lock.json
  lite/package.json
  src/main/java/oss/fosslight/api/advice/ApiV2ExceptionAdvice.java
  src/main/java/oss/fosslight/api/controller/lite/LiteDashboardController.java
  src/main/java/oss/fosslight/api/controller/lite/LiteLicenseController.java
  src/main/java/oss/fosslight/api/controller/lite/LiteOssController.java
  src/main/java/oss/fosslight/api/controller/lite/LiteProjectController.java
  src/main/java/oss/fosslight/api/controller/lite/LiteVulnerabilityController.java
  src/main/java/oss/fosslight/api/controller/v2/ApiProjectV2Controller.java
  src/main/java/oss/fosslight/api/dto/LicenseDto.java
  src/main/java/oss/fosslight/api/dto/ListLicenseDto.java
  src/main/java/oss/fosslight/api/dto/ListOssDto.java
  src/main/java/oss/fosslight/api/dto/ListVulnerabilityDto.java
  src/main/java/oss/fosslight/api/dto/OssDto.java
  src/main/java/oss/fosslight/api/dto/Paging.java
  src/main/java/oss/fosslight/api/dto/SortDirection.java
  src/main/java/oss/fosslight/api/dto/VulnerabilityDto.java
  src/main/java/oss/fosslight/common/CorsFilter.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/config/LiteAuthenticationEntryPoint.java
  src/main/java/oss/fosslight/config/SecurityConfig.java
  src/main/java/oss/fosslight/repository/ApiLicenseMapper.java
  src/main/java/oss/fosslight/repository/ApiOssMapper.java
  src/main/java/oss/fosslight/repository/ApiVulnerabilityMapper.java
  src/main/java/oss/fosslight/service/ApiLicenseService.java
  src/main/java/oss/fosslight/service/ApiOssService.java
  src/main/java/oss/fosslight/service/ApiVulnerabilityService.java
  src/main/java/oss/fosslight/service/impl/ApiLicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ApiOssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ApiVulnerabilityServiceImpl.java
  src/main/resources/oss/fosslight/repository/ApiLicenseMapper.xml
  src/main/resources/oss/fosslight/repository/ApiOssMapper.xml
  src/main/resources/oss/fosslight/repository/ApiVulnerabilityMapper.xml
Labels: Add

#53 Implement Self-Check project's CRUD (#52)
  lite/.eslintrc.json
  lite/@types/globals.d.ts
  lite/app/(auth)/sign-in/page.tsx
  lite/app/(main)/layout.tsx
  lite/app/(main)/self-check/[id]/page.tsx
  lite/app/(main)/self-check/page.tsx
  lite/components/detail-modal.tsx
  lite/components/editor.tsx
  lite/components/modal.tsx
  lite/components/self-check-modal.tsx
  lite/components/self-check-oss-modal.tsx
  lite/components/self-check-oss.tsx
  lite/components/top-bar.tsx
  lite/package-lock.json
  lite/package.json
Labels: Add

#55 Implement Self-Check project's notice features (#54)
  lite/app/(main)/layout.tsx
  lite/app/(main)/self-check/[id]/page.tsx
  lite/components/editor.tsx
  lite/components/modal.tsx
  lite/components/self-check-modal.tsx
  lite/components/self-check-notice.tsx
  lite/lib/hooks.ts
Labels: Add

#63 Implement selfcheck listing and oss listing in selfcheck
  src/main/java/oss/fosslight/api/controller/lite/LiteSelfCheckController.java
  src/main/java/oss/fosslight/api/dto/ListSelfCheckDto.java
  src/main/java/oss/fosslight/api/dto/ListSelfCheckOssDto.java
  src/main/java/oss/fosslight/api/dto/OssDetailsDto.java
  src/main/java/oss/fosslight/api/dto/OssDto.java
  src/main/java/oss/fosslight/api/dto/SelfCheckDto.java
  src/main/java/oss/fosslight/api/dto/SelfCheckOssDto.java
  src/main/java/oss/fosslight/repository/ApiSelfCheckMapper.java
  src/main/java/oss/fosslight/service/ApiSelfCheckService.java
  src/main/java/oss/fosslight/service/impl/ApiSelfCheckServiceImpl.java
  src/main/resources/oss/fosslight/repository/ApiLicenseMapper.xml
  src/main/resources/oss/fosslight/repository/ApiSelfCheckMapper.xml
Labels: Add

#67 Implement api for oss list in package tab of self-check (#62)
  src/main/java/oss/fosslight/api/controller/lite/LiteSelfCheckController.java
  src/main/java/oss/fosslight/api/dto/ListSelfCheckVerifyOssDto.java
  src/main/java/oss/fosslight/api/dto/OssDto.java
  src/main/java/oss/fosslight/api/dto/SelfCheckFileListDto.java
  src/main/java/oss/fosslight/repository/ApiSelfCheckMapper.java
  src/main/java/oss/fosslight/repository/VerificationMapper.java
  src/main/java/oss/fosslight/service/ApiSelfCheckService.java
  src/main/java/oss/fosslight/service/ApiVerificationService.java
  src/main/java/oss/fosslight/service/impl/ApiSelfCheckServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ApiVerificationServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/oss/fosslight/repository/ApiSelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/FileMapper.xml
  src/main/resources/oss/fosslight/repository/VerificationMapper.xml
Labels: Add

#68 Integrate API from backend with frontend (#47)
  lite/@types/globals.d.ts
  lite/app/(main)/database/license/page.tsx
  lite/app/(main)/self-check/[id]/page.tsx
  lite/app/(main)/self-check/page.tsx
  lite/components/detail-modal-license.tsx
  lite/components/detail-modal-oss.tsx
  lite/components/detail-modal-vuln.tsx
  lite/components/self-check-notice.tsx
  lite/components/self-check-oss-filters.tsx
  lite/components/self-check-oss-modal.tsx
  lite/components/self-check-oss.tsx
  lite/components/self-check-package.tsx
  lite/lib/hooks.ts
Labels: Add

#71 Add packages to selfcheck api output (#69)
  lite/@types/globals.d.ts
  lite/app/(main)/self-check/page.tsx
  lite/components/self-check-package.tsx
  src/main/java/oss/fosslight/api/dto/SelfCheckDto.java
  src/main/java/oss/fosslight/service/impl/ApiSelfCheckServiceImpl.java
  src/main/resources/oss/fosslight/repository/ApiSelfCheckMapper.xml
Labels: Add

#74 Integrate API from backend with frontend (#47)
  lite/@types/globals.d.ts
  lite/components/self-check-oss.tsx
Labels: Add

#73 Implement apis for autocompletion (#72)
  src/main/java/oss/fosslight/api/controller/lite/LiteLicenseController.java
  src/main/java/oss/fosslight/api/controller/lite/LiteOssController.java
  src/main/java/oss/fosslight/repository/ApiLicenseMapper.java
  src/main/java/oss/fosslight/repository/ApiOssMapper.java
  src/main/resources/oss/fosslight/repository/ApiLicenseMapper.xml
  src/main/resources/oss/fosslight/repository/ApiOssMapper.xml
Labels: Add

#76 Integrate API from backend with frontend (#47)
  lite/app/(main)/layout.tsx
  lite/components/self-check-oss-modal.tsx
  lite/components/self-check-oss-pagination.tsx
  lite/components/self-check-oss.tsx
  lite/package-lock.json
  lite/package.json
Labels: Add

#77 Integrate API from backend with frontend (#47)
  lite/components/modal.tsx
  lite/components/self-check-oss.tsx
  lite/components/self-check-package.tsx
Labels: Improve

#78 Integrate API from backend with frontend (#47)
  lite/app/(auth)/sign-in/page.tsx
  lite/app/(auth)/sign-up/page.tsx
Labels: Add

#80 Implement oss/license verification apis for self-check (#79)
  src/main/java/oss/fosslight/api/controller/lite/LiteSelfCheckController.java
  src/main/java/oss/fosslight/api/dto/FileDto.java
  src/main/java/oss/fosslight/api/dto/SelfCheckVerifyLicensesDto.java
  src/main/java/oss/fosslight/api/dto/SelfCheckVerifyOssDto.java
  src/main/java/oss/fosslight/service/ApiSelfCheckService.java
  src/main/java/oss/fosslight/service/impl/ApiSelfCheckServiceImpl.java
  src/main/java/oss/fosslight/validation/T2CoValidator.java
Labels: Add

#82 Implement apis for frontpage (81#)
  src/main/java/oss/fosslight/api/controller/lite/LiteDashboardController.java
  src/main/java/oss/fosslight/api/dto/Paging.java
  src/main/java/oss/fosslight/api/dto/SearchAllDto.java
  src/main/java/oss/fosslight/repository/ApiLicenseMapper.java
  src/main/java/oss/fosslight/repository/ApiOssMapper.java
  src/main/java/oss/fosslight/repository/ApiVulnerabilityMapper.java
  src/main/resources/oss/fosslight/repository/ApiLicenseMapper.xml
  src/main/resources/oss/fosslight/repository/ApiOssMapper.xml
  src/main/resources/oss/fosslight/repository/ApiVulnerabilityMapper.xml
Labels: Add

#88 Add groupby query/flag for oss search in dashboard (#81)
  src/main/java/oss/fosslight/api/controller/lite/LiteDashboardController.java
  src/main/java/oss/fosslight/service/ApiOssService.java
  src/main/java/oss/fosslight/service/impl/ApiOssServiceImpl.java
  src/main/resources/oss/fosslight/repository/ApiOssMapper.xml
Labels: Add

#89 Integrate API from backend with frontend (#47)
  lite/@types/globals.d.ts
  lite/app/(main)/page.tsx
  lite/app/(main)/search/page.tsx
  lite/app/(main)/self-check/[id]/check/page.tsx
  lite/components/list-sections.tsx
  lite/components/list-table.tsx
  lite/components/self-check-notice.tsx
  lite/components/self-check-oss.tsx
Labels: Add

#90 Integrate API from backend with frontend (#47)
  lite/app/(main)/self-check/page.tsx
  lite/components/modal.tsx
Labels: Add

#92 Implement api for email notification for license, and test for it (#91)
  migration/migration/scripts/20231217092243_update_v1.6.2.sql
  src/main/java/oss/fosslight/api/controller/lite/LiteSelfCheckController.java
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/ApiSelfCheckService.java
  src/main/java/oss/fosslight/service/impl/ApiSelfCheckServiceImpl.java
  src/main/resources/application.test.properties
  src/main/resources/template/email/licenseInvalidNotify.html
  src/test/java/oss/fosslight/controller/LiteSelfCheckTest.java
Labels: Add

#94 Implement api for downloading license/oss rows (#93)
  lite/app/(main)/database/license/page.tsx
  lite/app/(main)/database/oss/page.tsx
  service/template/LicenseList.xlsx
  service/template/OssList.xlsx
  src/main/java/oss/fosslight/api/controller/lite/LiteLicenseController.java
  src/main/java/oss/fosslight/api/controller/lite/LiteOssController.java
  src/main/java/oss/fosslight/api/dto/ExcelData.java
  src/main/java/oss/fosslight/api/dto/LicenseDto.java
  src/main/java/oss/fosslight/api/dto/OssDto.java
  src/main/java/oss/fosslight/service/ApiLicenseService.java
  src/main/java/oss/fosslight/service/ApiOssService.java
  src/main/java/oss/fosslight/service/impl/ApiLicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ApiOssServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/resources/oss/fosslight/repository/ApiLicenseMapper.xml
  src/main/resources/oss/fosslight/repository/ApiOssMapper.xml
Labels: Add

#96 Fix excel export (#95)
  src/main/java/oss/fosslight/api/dto/LicenseDto.java
  src/main/java/oss/fosslight/api/dto/OssDto.java
Labels: Fix

#97 Integrate API from backend with frontend (#47)
  lite/@types/globals.d.ts
  lite/app/(auth)/reset-password/page.tsx
  lite/app/(auth)/sign-in/page.tsx
  lite/app/(main)/database/license/page.tsx
  lite/app/(main)/database/oss/page.tsx
  lite/app/(main)/layout.tsx
  lite/app/(main)/self-check/[id]/check/page.tsx
  lite/app/(main)/self-check/page.tsx
  lite/components/input-with-autocomplete.tsx
  lite/components/list-table.tsx
  lite/components/self-check-notice-warning-modal.tsx
  lite/components/self-check-notice.tsx
  lite/components/self-check-oss-modal.tsx
  lite/components/self-check-oss.tsx
  lite/package-lock.json
  lite/package.json
Labels: Improve

#105 Implement user/division api + bugfixes (#104)
  src/main/java/oss/fosslight/api/controller/lite/LiteSelfCheckController.java
  src/main/java/oss/fosslight/api/controller/lite/LiteUserController.java
  src/main/java/oss/fosslight/api/dto/ListSelfCheckDto.java
  src/main/java/oss/fosslight/api/dto/OssDetailsDto.java
  src/main/java/oss/fosslight/api/dto/SelfCheckDto.java
  src/main/java/oss/fosslight/api/dto/UserDto.java
  src/main/java/oss/fosslight/config/SecurityConfig.java
  src/main/java/oss/fosslight/service/impl/ApiSelfCheckServiceImpl.java
  src/main/resources/oss/fosslight/repository/ApiSelfCheckMapper.xml
Labels: Add

#106 Integrate API from backend with frontend (#47)
  docker-compose.yml
  lite/Dockerfile
  lite/app/(auth)/sign-in/page.tsx
  lite/app/(auth)/sign-up/page.tsx
  lite/app/(main)/database/license/page.tsx
  lite/app/(main)/database/oss/page.tsx
  lite/app/(main)/database/vulnerability/page.tsx
  lite/app/(main)/layout.tsx
  lite/app/(main)/page.tsx
  lite/app/(main)/search/page.tsx
  lite/app/(main)/self-check/[id]/check/page.tsx
  lite/app/(main)/self-check/[id]/page.tsx
  lite/app/(main)/self-check/page.tsx
  lite/components/detail-modal-license.tsx
  lite/components/detail-modal-oss.tsx
  lite/components/detail-modal-vuln.tsx
  lite/components/self-check-modal.tsx
  lite/components/self-check-notice.tsx
  lite/components/self-check-oss-modal.tsx
  lite/components/self-check-oss.tsx
  lite/components/self-check-package.tsx
  lite/lib/hooks.ts
  lite/lib/literals.ts
Labels: Add
